version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepbazar-client
    ports:
      - '4093:4093'
    volumes:
      - .:/app
      - /app/node_modules
