// products category list
export const categoryList = [
  {
    id: 1,
    category: "All",
    img: "https://png.pngtree.com/png-vector/20190703/ourlarge/pngtree-shopping-bag-icon-in-trendy-style-isolated-background-png-image_1536177.jpg",
    link: "",
  },
  {
    id: 2,
    category: "Men's Clothes",
    img: "https://png.pngtree.com/png-vector/20190703/ourlarge/pngtree-shopping-bag-icon-in-trendy-style-isolated-background-png-image_1536177.jpg",
    link: "/men-clothes",
    categoryList: [
      {
        id: 1,
        text: "A",
        link: "/lala",
      },
      {
        id: 2,
        text: "Alala",
        link: "/lala",
      },
      {
        id: 3,
        text: "gfhgdf",
        link: "/dadf",
      },
      {
        id: 4,
        text: "sd",
        link: "/dadddaf",
      },
      {
        id: 5,
        text: "sfa sdf d",
        link: "/dadddaf",
      },
    ],
  },
  {
    id: 3,
    category: "Women's Clothes",
    img: "https://png.pngtree.com/png-vector/20190703/ourlarge/pngtree-shopping-bag-icon-in-trendy-style-isolated-background-png-image_1536177.jpg",
    link: "/women-clothes",
    categoryList: [
      {
        id: 1,
        text: "A",
        link: "/lala",
      },
      {
        id: 2,
        text: "Alala",
        link: "/lala",
      },
      {
        id: 3,
        text: "gfhgdf",
        link: "/dadf",
      },
      {
        id: 4,
        text: "sd",
        link: "/dadddaf",
      },
      {
        id: 5,
        text: "sfa sdf d",
        link: "/dadddaf",
      },
    ],
  },
  {
    id: 4,
    category: "Bags",
    img: "https://png.pngtree.com/png-vector/20190703/ourlarge/pngtree-shopping-bag-icon-in-trendy-style-isolated-background-png-image_1536177.jpg",
    link: "/bags",
    categoryList: [
      {
        id: 1,
        text: "A",
        link: "/lala",
      },
      {
        id: 2,
        text: "Alala",
        link: "/lala",
      },
      {
        id: 3,
        text: "gfhgdf",
        link: "/dadf",
      },
      {
        id: 4,
        text: "sd",
        link: "/dadddaf",
      },
      {
        id: 5,
        text: "sfa sdf d",
        link: "/dadddaf",
      },
    ],
  },
  {
    id: 5,
    category: "Toys",
    img: "https://png.pngtree.com/png-vector/20190703/ourlarge/pngtree-shopping-bag-icon-in-trendy-style-isolated-background-png-image_1536177.jpg",
    link: "/toys",
    categoryList: [
      {
        id: 1,
        text: "A",
        link: "/lala",
      },
      {
        id: 2,
        text: "Alala",
        link: "/lala",
      },
      {
        id: 3,
        text: "gfhgdf",
        link: "/dadf",
      },
      {
        id: 4,
        text: "sd",
        link: "/dadddaf",
      },
      {
        id: 5,
        text: "sfa sdf d",
        link: "/dadddaf",
      },
    ],
  },

  {
    id: 6,
    category: "Baby and Kids",
    img: "https://png.pngtree.com/png-vector/20190703/ourlarge/pngtree-shopping-bag-icon-in-trendy-style-isolated-background-png-image_1536177.jpg",
    link: "/baby-and-kids",
    categoryList: [
      {
        id: 1,
        text: "A",
        link: "/lala",
      },
      {
        id: 2,
        text: "Alala",
        link: "/lala",
      },
      {
        id: 3,
        text: "gfhgdf",
        link: "/dadf",
      },
      {
        id: 4,
        text: "sd",
        link: "/dadddaf",
      },
      {
        id: 5,
        text: "sfa sdf d",
        link: "/dadddaf",
      },
    ],
  },
];

// pages links
export const links = [
  {
    id: 1,
    name: "Home",
    link: "/",
  },
  {
    id: 2,
    name: "All Products",
    link: "/shop",
  },
  {
    id: 3,
    name: "Customer Services",
    link: "/services",
  },
  {
    id: 4,
    name: "Help Center",
    link: "/help",
  },
];

export const products = [
  {
    id: 1,
    category: "men-clothes",
    title: "Men's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 5,
    currency: "৳",
    discountOffer: "11",
    newProduct: false,
    topSelling: true,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 2,
    category: "women-clothes",
    title: "Women's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 11,
    currency: "৳",
    discountOffer: "",
    newProduct: false,
    topSelling: true,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 3,
    category: "bags",
    title: "Styles Bags 1",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 20,
    currency: "৳",
    discountOffer: "3",
    newProduct: false,
    topSelling: true,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 4,
    category: "baby-and-kids",
    title: "baby's t-shirt",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "",
    newProduct: false,
    topSelling: true,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 5,
    category: "bags",
    title: "Big tadybear Bags",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 199.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "23",
    newProduct: false,
    topSelling: true,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 6,
    category: "toys",
    title: "toys lala",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 29.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "11",
    newProduct: false,
    topSelling: true,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 7,
    category: "women-clothes",
    title: "Sari",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "",
    newProduct: false,
    topSelling: true,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 8,
    category: "men-clothes",
    title: "Men's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "3",
    newProduct: false,
    topSelling: true,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 9,
    category: "men-clothes",
    title: "Men's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "",
    newProduct: false,
    topSelling: false,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 10,
    category: "women-clothes",
    title: "Women's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "23",
    newProduct: true,
    topSelling: false,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 11,
    category: "men-clothes",
    title: "Men's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "11",
    newProduct: false,
    topSelling: false,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 12,
    category: "women-clothes",
    title: "Women's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "",
    newProduct: false,
    topSelling: false,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 13,
    category: "women-clothes",
    title: "Men's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "3",
    newProduct: true,
    topSelling: false,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 14,
    category: "men-clothes",
    title: "Men's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "",
    newProduct: false,
    topSelling: false,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 15,
    category: "women-clothes",
    title: "Women's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "23",
    newProduct: true,
    topSelling: false,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 16,
    category: "men-clothes",
    title: "Men's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "11",
    newProduct: false,
    topSelling: false,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 17,
    category: "women-clothes",
    title: "Women's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "",
    newProduct: false,
    topSelling: true,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 18,
    category: "women-clothes",
    title: "Men's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "3",
    newProduct: true,
    topSelling: false,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 19,
    category: "men-clothes",
    title: "Men's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "",
    newProduct: true,
    topSelling: false,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 20,
    category: "women-clothes",
    title: "Women's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "23",
    newProduct: true,
    topSelling: false,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 21,
    category: "women-clothes",
    title: "Men's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "3",
    newProduct: true,
    topSelling: false,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 22,
    category: "men-clothes",
    title: "Men's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "",
    newProduct: true,
    topSelling: false,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
  {
    id: 23,
    category: "women-clothes",
    title: "Women's Clothes jackets",
    images: ["lad", "kads", "akdsjf", "kadsfa", "laksd"],
    available: "In Stock",
    price: 299.0,
    minQuantity: 10,
    currency: "৳",
    discountOffer: "23",
    newProduct: true,
    topSelling: false,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur voluptas nam consectetur perspiciatis harum quis rerum nemo aliquid doloribus recusandae incidunt reiciendis sequi, similique, sit inventore repellendus ipsam dignissimos voluptate?",
  },
];
