#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '👀👀👀Testing and building this project before commiting👀👀👀'

## ---------------------------------------------------
yarn lint:fix ||
(
    echo 'Eslint file fixing failed'
    false 
)
echo "success ✅✅✅✅✅✅"


##----------------------------------------------------
yarn lint ||
(
    echo 'Eslint check failed'
    false;
)
echo "success ✅✅✅✅✅✅"


##----------------------------------------------------
yarn prettier:fix ||
(
    echo "Can't format code"
    false;
)
echo "success ✅✅✅✅✅✅"


##----------------------------------------------------
yarn prettier ||
(
    echo 'The format is disgusting'
    false;
)
echo "success ✅✅✅✅✅✅"


#If everything passes... try to run build
echo 'Your code looks good ---> trying to build it now👍👍👍👍👍👍'
##----------------------------------------------------
yarn build ||
(
    echo 'Your next build failed'
    false;
)
echo "PROJECT BUILT SUCCESSFULLY COMPLETE 😎😎😎😎😎😎"
